### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TheAlot** [TheAlot/TheAlot.github.io#3]
- [ ] Add style to disabled state text
- [ ] Add loading animation
- [ ] Add the rest of the color schemes from [the react version](https://caferati.me/demo/react-awesome-button)
